repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: poetry run flake8 -j auto
        language: system
        types: [python]

      - id: isort
        name: isort
        entry: poetry run isort
        language: system
        types: [python]
        args: ["--filter-files"]

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks
