# Qlty Configuration
# Learn more at https://docs.qlty.sh
config_version = "0"

# Plugins configuration
[[plugin]]
name = "actionlint"

[[plugin]]
name = "trufflehog"

[[plugin]]
name = "osv-scanner"

# Source configuration
[[source]]
name = "default"
default = true

# Exclusion patterns
exclude_patterns = [
  "__pycache__/",
  "*.py[cod]",
  "*$py.class",
  ".pytest_cache/",
  ".nox/",
  "*.egg-info/",
  ".venv/",
  "venv/",
  "env/",
  "ENV/",
  ".tox/",
  ".mypy_cache/",
  ".hypothesis/",
  "dist/",
  "build/",
  "coverage/",
  "htmlcov/",
  ".git/**",
  "*.min.js",
  "*.min.css",
]

# Code Smells Configuration
[smells]
mode = "block"

[smells.boolean_logic]
enabled = true
threshold = 4

[smells.nested_control_flow]
enabled = true
threshold = 4

[smells.function_parameters]
enabled = true
threshold = 5

[smells.function_length]
enabled = true
threshold = 50

[smells.file_length]
enabled = true
threshold = 500

[smells.cognitive_complexity]
enabled = true
threshold = 15

[smells.duplicate_code]
enabled = true
threshold = 6

[smells.large_class]
enabled = true
threshold = 500

[smells.long_parameter_list]
enabled = true
threshold = 2
